#!/bin/bash

for i in *.mod ; do
   echo " "
   echo "$ cat $i"
   cat $i
   echo " "
   echo "$ gm2 -fsoft-check-all -O2 -fanalyzer -c -g $i"
   gm2 -fsoft-check-all -fanalyzer -c -g $i
done

for i in callbyref*.mod ; do
   echo " "
   echo "$ cat $i"
   cat $i
   echo " "
   echo "$ gm2 -O2 -fsoft-check-all -fanalyzer -c -g $i"
   gm2 -O2 -fsoft-check-all -fanalyzer -c -g $i
done

